MAIN_URL = "https://stellarburgers.nomoreparties.site/"
EMAIL = "zurujaltest@gmail.com"
PASSWORD = "12345678"
CONTAINS = "Cостав"
CONFIRMED_ORDER = "Ваш заказ начали готовить"
COUNTER = "2"
BURGER_HEADER = "Соберите бургер"
ORDER_HISTORY_HEADER = "Лента заказов"
INGREDIENT_HEADER = "Детали ингредиента"
ENTER_BUTTON = "Войти"
RESTORE_BUTTON = "Восстановить"
ORDER_PAGE_HEADER = "Лента заказов"
SAVE_BUTTON = "Сохранить"
PASSWORD_CHECK = "Пароль"
VALUE = "9999"

